# Generated by Django 4.2.11 on 2026-03-11 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('prospect', 'Prospect'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/logos/%Y/%m/')),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_clients', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.OneToOneField(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('client',), name='unique_primary_contact_per_client'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'industry'], name='clients_cli_status_30bd04_idx'),
        ),
    ]
